[application]
name = "cream"
default_platform = "web"

[web.app]
title = "CREAM - CURD Retail Exchange And Marketplace"

[web.watcher]
watch_path = ["src", "input.css"]

[mobile]
bundle_identifier = "com.cream.marketplace"
version = "0.1.0"
